config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    get "users/sign_out" => "users/sessions#destroy"
  end
  root "events#index"
  resources :events
  resources :events do
    post 'attend', on: :member
  end
  resources :events do
    get 'attend', on: :member
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "creator_id"
    has_many :attendances
    has_many :attendees, through: :attendances, source: :user

    scope :upcoming, -> { where('date > ?', Time.now) }
    scope :past, -> { where('date < ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :events, foreign_key: :creator_id, class_name: 'Event'       
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :authenticate_user!, except: :index

    def index
        @upcoming = Event.upcoming
        @past = Event.past
    end 
    
    def new 
        @event = Event.new
    end
    
    def create
        @event = current_user.events.build(event_params)

        if @event.save
            redirect_to events_path
        else 
            render :new, status: :unprocessable_entity
        end
    end

    def show
        @event = Event.find(params[:id])
    end 
    
    def attend
        @event = Event.find(params[:id])
        
        # Prevent user from attending the event more than once
        if @event.attendees.exclude?(current_user)
          @event.attendees << current_user
          flash[:notice] = "You are now attending this event."
        else
          flash[:alert] = "You are already attending this event."
        end
    
        redirect_to events_path
      end
    private

    def event_params
        params.require(:event).permit(:title, :location, :date)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @created_events = Event.where(creator_id: @user.id).all
        @past_events = @user.attended_events.past
        @upcoming_events = @user.attended_events.upcoming
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events List</h1>

<p><strong>Upcoming Events</strong></p>
<% @upcoming.each do |event| %>
    <div style=border:solid>  
        <p><%= link_to event.title, event %></p>
        <p><%= link_to event.creator.email, event.creator %></p>        
    </div><br>
<% end %>

<p><strong>Past Events</strong></p>
<% @past.each do |event| %>
    <div style=border:solid>  
        <p><%= link_to event.title, event %></p>
        <p><%= link_to event.creator.email, event.creator %></p>        
    </div><br>
<% end %>

<% if user_signed_in? %>
    <p>Create a new event <%= link_to "here", new_event_path %></p>
    <p>Sign out <%= link_to "here", destroy_user_session_path, method: :delete %></p>
<% else %>
    <p>Sign in <%= link_to "here", user_session_path %></p>
<% end %>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>

    <div>
        <%= form.label :title, "Title" %>
        <%= form.text_field :title, default: "Prepopulated Value", size: 20 %>
    </div><br> 
    <div>
        <%= form.label :location, "Location" %>
        <%= form.text_field :location, default: "Prepopulated Value", size: 20 %>
    </div><br>    
    <div>
        <%= form.label :date, "Date" %>
        <%= form.date_field :date %>
        <%= form.submit %>
    </div>    
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<div>    
    <p>Location: <%= @event.location %></p>
    <p>Date: <%= @event.date %></p>
    <p>Creator: <%= @event.creator.email %></p>
</div><br>

<% if current_user != @event.creator %>
  <% if @event.attendees.include?(current_user) %>
    <p>You are attending this event!</p>
  <% else %>
    <%= link_to 'Attend Event', attend_event_path(@event), method: :post, class: "btn btn-primary" %>
  <% end %>
<% end %>

<h3>Attendees:</h3>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.email %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<p><strong>Created Events</strong></p>
<% @created_events.each do |event| %>
    <div>
        <p>Title: <%= event.title %></p> 
        <p>Location: <%= event.location %></p>
        <p>Date: <%= event.date %></p>
    </div><br>
<% end %>

<p><strong>Upcoming Events</strong></p>
<% @upcoming_events.each do |event| %>
    <div>
        <p><%= link_to event.title, event %></p>  
    </div><br>
<% end %>    

<p><strong>Past Events</strong></p>
<% @past_events.each do |event| %>
    <div>
        <p><%= link_to event.title, event %></p>  
    </div><br>
<% end %> 

<p><%= link_to "Main", events_path %></p>